### PR TITLE
Update jquery.center.js

### PR DESCRIPTION
**Pull request by billfeller**

### CODE REVIEW

**Comment by billfeller** [comment]
see the jQuery 1.7.1 source, when using .outerWidth(), it returns (parseFloat( jQuery.css( elem, type, margin ? "margin" : "border" ) )). so maybe .outerWidth(false) in jQuery-1.8.1 is better.

**Comment by ben-lin** [comment]
hey @billfeller from the [jquery outerWidth  doc](http://api.jquery.com/outerWidth/) passing `false` means not to include the margin value. I think it's irrelevant. Also I tested with 1.8.1 and it works fine :)

**Comment by billfeller** [comment]
yeah, i use jquery.ui.core.js that override $.fn.outerWidth(the version of jquery.ui.core.js that i use is too old). it return [object Object] when omits the parameter, but return number when get parameter. when i update the jquery.ui.core.js to the latest version, jquery.fn.center works ok!

thx.

billfeller

**Comment by billfeller** [comment]
```
    <script src="http://code.jquery.com/jquery-1.8.1.js"></script>
    <script src="./jquery.ui.core.js"></script><!-- use the latest version -->
    <script type="text/javascript">
        ;( function( $, window ){
          $.fn.center = function( options ){
            var $w, scrollTop;

            $w        = $( window ); // cache gobal
            scrollTop = $w.scrollTop();

            return this.each( function(){
              var $this, configs, centerize;

              $this = $( this ); // cache $( this )
              // merge user options with default configs
              configs = $.extend({
                against : 'window',
                top : false,
                topPercentage : 0.5
              }, options );

              centerize = function(){
                var against, $against, x, y;

                against = configs.against;

                if( against === 'window' ){
                  $against = $w;
                }else if( against === 'parent' ){
                  $against = $this.parent();
                  scrollTop = 0;
                }else{
                  $against = $this.parents( against );
                  scrollTop = 0;
                }

                x = (( $against.width()) - ( $this.outerWidth())) * 0.5;
                y = (( $against.height()) - ( $this.outerHeight())) * configs.topPercentage + scrollTop;

                if( configs.top ) y = configs.top + scrollTop;

                $this.css({
                  'left' : x,
                  'top' : y
                });
              };

              // apply centerization
              centerize();
              $w.resize( centerize );
            });
          };
        })( jQuery, window );

        $('<div id="center" style="position:absolute;display:none;">居中显示</div>').appendTo($('body')).show().center();
    </script>
```

**Pull request closed without merging**
